### PR TITLE
Adds the -ov flag which allows xwinwrap to work on non-Debian distros

### PR DESCRIPTION
**Pull request by gjgress**
I can't test on other distros to make sure this works, but this at least works on Arch. Discussion in #4 .

### CODE REVIEW

**Comment by NayamAmarshe** [comment]
This needs some work. Stops the app from working on debian based distros, which defeats the purpose. Instead of this, you could add a checkbox in the video wallpaper app to allow for a `-ov` flag to run.

**Comment by gjgress** [comment]
I'll see if I can find a way to test on other distros and play around with the flags. It's hard to determine what behavior is expected or unexpected because the flags aren't well documented in xwinwrap. Thanks for the feedback.

**Comment by gjgress** [comment]
As mentioned [here](https://github.com/ghostlexly/gpu-video-wallpaper/issues/4#issuecomment-1042579608), the issue seems to lie with how xwinwrap interacts with gnome (and likely Cinnamon as well).

My arch install uses KDE, which is why I didn't experience the issue. I would appreciate it if XFCE, LXQt (is this still used?), or i3 users can check if the flags also cause them issues.

If it turns out to be Gnome-specific, then I can rewrite the pull request to check if the DE is gnome-based and omit the flags if so, and otherwise include the flags.

I think this is the only thing in the way of cross-distro compatibility.

**Comment by ZediAlreadyTaken** [comment]
> My arch install uses KDE, which is why I didn't experience the issue. I would appreciate it if XFCE, LXQt (is this still used?), or i3 users can check if the flags also cause them issues.

I'm using Xfce on Arch Linux, the program ran fine before adding the -ov flag but nothing changed after I added it. I still cannot see my desktop icons on Xfce, they get hidden when I run the script.

**Comment by gjgress** [comment]
Unfortunate. `xwinwrap` is really the culprit here, and development on it is rather slow. I don't anticipate these problems being fixed anytime soon.

I wonder if there are any xwinwrap alternatives that can do the same job. Would also be nice if there was a Wayland compatible option.

**Comment by SwallowYourDreams** [comment]
I can confirm the issue for Linux Mint 20 x64 / Cinnamon. Adding the `-ov` flag will not lead to any crashes or errors, but will not show any video wallpaper.

**Comment by ghostlexly** [comment]
Closed as this will cause issue on Debian based distros.

**Pull request closed without merging**
